spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imooc_demo?characterEncoding=utf8&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true
    username: root
    password: chen
    driver-class-name: com.mysql.jdbc.Driver
# basic验证暂时关掉
#security:
#  basic:
#   enabled: false

imooc:
  security:
    browser:
      # 自定义登录页
      loginPage: /demo-signIn.html
      # 自定义返回方式 JSON | REDIRECT
      loginResponseType: JSON
      # 记住我过期时间
      rememberMeSeconds: 60
    code:
      #图形验证码配置
      image:
        # 图形验证码数字个数
        length: 6
        #过期时间
        expireIn: 65
        # 宽度 此配置覆盖了默认配置，如果在页面请求地址中带有width参数，则将覆盖此配置
        width: 50
        # 高度 此配置覆盖了默认配置，如果在页面请求地址中带有height参数，则将覆盖此配置
        height: 25
        # 要验证码验证的url:请求方式，":"分隔请求方式, ","分隔多个需验证地址，","之间不要有空格
        #url: /user:get,/user/*:*
      #短信验证码配置
      sms:
        #验证码长度
        length: 8
        #过期时间
        expireIn: 30
        # 要验证码验证的url:请求方式，":"分隔请求方式, ","分隔多个需验证地址，","之间不要有空格
        #url: /user:post,/user/*:get
    #不需做登陆验证的url，","分隔，","之间不要有空格
    permitUrls: /user/me,/user/*